[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
axum = "0.7.7"
dirs = "5.0.1"
mime = "0.3.17"
rusqlite = {version = "0.32.1", features = ["bundled"]}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["rt", "macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.18"
