[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.flow]
workspace = false
dependencies = ["member", "root"]

[tasks.member]
run_task = { name = "member_flow", fork = true }

[tasks.member_flow]
dependencies = ["clean", "build"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.root]
dependencies = ["move_to_release"]

[tasks.move_to_release]
windows_alias = "move_to_release_windows_alias"
alias = "move_to_release_alias"

[tasks.move_to_release_alias]
script_runner = "bash"
script = '''
source_dir="./target/release"
target_dir="./release"  

rm -rf "$target_dir"
mkdir -p "$target_dir"
cp -r ./static/* "$target_dir"
cp -r ./web/dist/* "$target_dir"


# 使用 find 命令查找符合条件的文件并复制
# find "$source_dir" -type f \( -name "*.exe" -o -name "*.[!.]*" \) -exec cp {} "$target_dir" \;
find "$source_dir" -type f \( -name "*.exe" -o ! -name "*.*" \) -exec cp -v {} "$target_dir" \;
# for file in ./target/release/*; do
#     # 检查是否是文件且没有后缀或后缀为 .exe
#     if [[ -f "$file" && (! "$file" =~ \. || "$file" =~ \.exe$) ]]; then
#         echo "Moving $file to $DEST_DIR"
#         cp "$file" "$DEST_DIR/"
#     fi
# done

'''

[tasks.move_to_release_windows_alias]
script_runner = "powershell"
script_extension = "ps1"
script = '''
$DEST_DIR = ".\release"
if (Test-Path -Path "$DEST_DIR") {
    Remove-Item -Path "$DEST_DIR" -Force -Recurse
}
New-Item -Path "$DEST_DIR" -ItemType Directory -Force
Copy-Item -Path ".\static\*" -Destination "$DEST_DIR" -Recurse
Copy-Item -Path ".\web\dist\*" -Destination "$DEST_DIR" -Recurse

$TARGET_RELEASE_FOLDER = ".\target\release"
$EXECUTOR_FILES = Get-ChildItem -Path $TARGET_RELEASE_FOLDER -File | Where-Object {
    $_.Extension -eq "" -or $_.Extension -eq ".exe"
}
foreach ($file in $EXECUTOR_FILES) {
    Copy-Item -Path $file.FullName -Destination $DEST_DIR
}
'''


