name: Deploy Server

on:
  push:
    branches:
      - main  # 或者你想要部署的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # 根据你的项目需求选择 Node.js 版本

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # 你可以选择其他工具链版本

    - name: Install cargo-make
      run: cargo install cargo-make

    - name: Install pnpm
      run: npm install -g pnpm && pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Create tar.gz
      run: |
        tar -zcvf server-auto-deploy-by-github.tar.gz ./release

    - name: Copy files to server # 上传压缩包至服务器
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }} # 若使用密码则删除本行
        port: ${{ secrets.SERVER_PORT }}
        source: "server-auto-deploy-by-github.tar.gz"
        target: "./"

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Deploying to server..."
          rm -rf ./server-auto-deploy-by-github
          # mkdir -p /server-auto-deploy-by-github
          tar -zxvf server-auto-deploy-by-github.tar.gz
          echo "Deployed to server!"