name: Deploy Server

on:
  push:
    branches:
      - main  # 或者你想要部署的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # 根据你的项目需求选择 Node.js 版本

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # 你可以选择其他工具链版本

    - name: Install pnpm
      run: npm install -g pnpm && pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Deploying to server..."
          mkdir -p /root/server-auto-deploy-by-github
          rm -rf /root/server-auto-deploy-by-github/*
          scp -r target/release /root/server-auto-deploy-by-github
          # scp -r target/release/server /root/server-auto-deploy-by-github
          # scp -r target/release/scripts /root/server-auto-deploy-by-github
          # scp -r target/release/index.html /root/server-auto-deploy-by-github
          # scp -r target/release/assets /root/server-auto-deploy-by-github
          echo "Deployed to server!"